version: '3.9'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATABASE: ${PG_DB}
      PGUSER: ${PG_USER}
      PGPASSWORD: ${PG_PASSWORD}
  redis:
    image: redis:latest
    restart: always
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
  web:
    build: .
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles/
      - ./media:/usr/src/app/media/
    ports:
      - 127.0.0.1:${WEB_PORT}:8000
    depends_on:
      - db
      - redis
volumes:
  db_data:
