# Generated by Django 4.0.7 on 2022-10-13 11:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclasspage',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='schoolclasspage',
            name='gallery_images',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='school_class', to='app.imagesgallarypage'),
        ),
    ]
