# Generated by Django 4.1.2 on 2022-10-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("app", "0002_imagesgallarypage_infopage_listpage_newsitemspage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="meta keywords"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="search image",
            ),
        ),
    ]
