# Generated by Django 4.1.2 on 2022-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_homepage_keywords_homepage_search_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
