# Generated by Django 4.0.7 on 2022-10-11 13:45

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('app', '0004_classpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassPage',
            new_name='SchoolClassPage',
        ),
        migrations.AddField(
            model_name='imagesgallarypage',
            name='school_class',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.schoolclasspage'),
        ),
    ]
