# Generated by Django 4.0.7 on 2022-10-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('app', '0005_profile_body_profile_image_delete_profilepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfilePage',
        ),
    ]
