# Generated by Django 4.0.7 on 2022-10-11 13:51

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_classpage_schoolclasspage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesgallarypage',
            name='school_class',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.schoolclasspage'),
        ),
    ]
