# Generated by Django 4.0.7 on 2022-10-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0076_modellogentry_revision'),
        ('app', '0006_rename_profile_profilepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='surname',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('super_user', 'Super user'), ('admin', 'Admin')], max_length=80)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='app.schoolclasspage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='app.profile'),
        ),
    ]
