# Generated by Django 4.1.3 on 2022-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_formpage_alter_homepage_search_image_formfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
