# Generated by Django 4.0.7 on 2022-10-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('app', '0006_alter_imagesgallarypage_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('super_user', 'super_user'), ('admin', 'admin')], max_length=80)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='app.schoolclasspage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
