# Generated by Django 4.1.3 on 2022-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
