# Generated by Django 4.0.7 on 2022-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lessonpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('super_user', 'super user'), ('admin', 'admin')], max_length=80),
        ),
    ]
