# Generated by Django 4.0.7 on 2022-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('about_us', 'About_us'), ('contacts', 'Contacts')], default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('super_user', 'Super user'), ('admin', 'Admin')], max_length=80),
        ),
    ]
