# Generated by Django 4.1.3 on 2022-12-01 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_candiadate"),
    ]

    operations = [
        migrations.AddField(
            model_name="candiadate",
            name="career_object",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.career"
            ),
        ),
        migrations.AlterField(
            model_name="candiadate",
            name="phone_number",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone_number",
                        message="Input correcr phone number XXX-XXX-XX-XX",
                        regex="\\d{3}-\\d{3}-\\d{2}-\\d{2}",
                    )
                ],
            ),
        ),
    ]
