# Generated by Django 4.1.3 on 2022-12-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_projectspage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candiadate",
            name="cv",
        ),
        migrations.AddField(
            model_name="candiadate",
            name="cv_file",
            field=models.BinaryField(default=b"default value", editable=True),
        ),
        migrations.AddField(
            model_name="candiadate",
            name="cv_file_name",
            field=models.CharField(default="default cv file name", max_length=255),
        ),
    ]
