# Generated by Django 4.1.3 on 2022-12-02 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_candiadate_cv_candiadate_cv_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
