from app.models.user import User  # noqa: F401
from app.models.home_page import HomePage  # noqa: F401
from app.models.images_gallary_page import ImagesGallaryPage  # noqa: F401
from app.models.info_page import InfoPage  # noqa: F401
from app.models.lesson_page import LessonPage  # noqa: F401
from app.models.list_page import ListPage  # noqa: F401
from app.models.news_items_page import NewsItemsPage  # noqa: F401
from app.models.profile_page import ProfilePage  # noqa: F401
from app.models.profile import Profile  # noqa: F401
from app.models.schedule_page import SchedulePage  # noqa: F401
from app.models.school_class_page import SchoolClassPage  # noqa: F401
from app.models.social_app_admin import SocialAppAdmin  # noqa: F401
from app.models.social_auth_group import SocialAuthGroup  # noqa: F401
